/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import game.exceptions.CheaterException;
import game.exceptions.OutOfBoardException;
import game.exceptions.SymbolAlreadyThereException;
import game.GUIGame;
import game.board.Board;
import game.board.BoardSymbol;
import game.player.InteligentPlayer;
import game.player.Move;
import game.player.Player1;
import game.player.Player3;
import game.player.Sta0445;
import game.player.StupidPlayer;
import game.tournament.Player;
import game.tournament.Tournament;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author lukstankovic
 */
public class Window extends javax.swing.JFrame {

	/**
	 * Creates new form Window
	 */
	public Window() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("jRadioButtonMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Piškvorky");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("10");

        jLabel1.setText("Velikost plochy:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Uživatel první");
        jRadioButton1.setName("humanFirstRadioButton"); // NOI18N

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Počítač první");
        jRadioButton2.setName("PCFirstRadioButton"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(701, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

	GUIGame game;
	
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (game == null || isGameOver) {
			isGameOver = false;
			jLabel2.setText("");
			boardSize = Integer.parseInt(jTextField1.getText());
			humanFirst = jRadioButton1.isSelected();
			game = new GUIGame(boardSize, new Sta0445());
			repaint();
			if (!humanFirst) {
				PCMove();
			}
		} 
		
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
		if (game != null && !isGameOver) {
			int positionOnBoardX = (evt.getX() - topXShift) / ((this.getWidth() - topXShift - bottomXShift)/boardSize);
			int positionOnBoardY = (evt.getY() - topYShift) / ((this.getHeight() - topYShift - bottomYShift)/boardSize);
			
			do {
				repaint();
			} while(!isGameOver && humanMove(positionOnBoardX, positionOnBoardY));

			repaint();
			do {
				repaint();
			} while(!isGameOver && PCMove());
			
		}
    }//GEN-LAST:event_formMouseReleased
	
	
	private boolean humanMove(int posX, int posY) {
		if (game.makeMove(new Move(posX, posY, BoardSymbol.CIRCLE))) {
			jLabel2.setForeground(Color.black);
			jLabel2.setText("Vyhrál jsi!");
			repaint();
			isGameOver = true;
			jButton1.setText("Nová hra");
			return true;
		} 
		return false;
	}
	
	private boolean PCMove() {
		if(game.makeMove(BoardSymbol.CROSS)) {
			jLabel2.setForeground(Color.red);
			jLabel2.setText("Vyhrál počítač!");
			repaint();
			isGameOver = true;
			jButton1.setText("Nová hra");
			return true;
		}
		return false;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/*ArrayList<Player> players = new ArrayList<>();
		players.add(new Player(new StupidPlayer()));
		players.add(new Player(new StupidPlayer()));
		players.add(new Player(new StupidPlayer()));
		players.add(new Player(new StupidPlayer()));
		players.add(new Player(new StupidPlayer()));
		players.add(new Player(new StupidPlayer()));
		players.add(new Player(new StupidPlayer()));
		players.add(new Player(new StupidPlayer()));
		players.add(new Player(new Sta0445()));
		
		
		Tournament t = new Tournament(players);
		System.out.println(t);
		t.playTournament();
		System.out.println(t);
		*/
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Window().setVisible(true);
			}
		});
	}

	private final int topXShift = 20;
	private final int topYShift = 30;
	private final int bottomXShift = 200;
	private final int bottomYShift = 20;
	private int boardSize = 10;
	private boolean isGameOver = false;
	private boolean humanFirst = true;

	@Override
	public void paint(Graphics g) {
		super.paint(g);
		if (game != null) {
			paintBackground(g);
			paintSymbols(g);
		}
	}


	private void paintBackground(Graphics g) {
		int sizeX = this.getWidth() - topXShift - bottomXShift;
		int sizeY = this.getHeight() - topYShift - bottomYShift;
		for (int i = 0; i <= boardSize; i++) {
			int lineXPosition = (int)(((double)sizeX/boardSize) * i) + topXShift;
			g.drawLine(lineXPosition, topYShift, lineXPosition, topYShift + sizeY);
			int lineYPosition = (int)(((double)sizeY/boardSize) * i) + topYShift;
			g.drawLine(topXShift, lineYPosition, topXShift + sizeX, lineYPosition);
		}
	
		
	}
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

	private void paintSymbols(Graphics g) {
		Board board = game.getBoard();
		for (int i = 0; i < boardSize; i++) {
			for (int j = 0; j < boardSize; j++) {
				if (board.getSymbolAtPosition(i, j) == BoardSymbol.CIRCLE) {
					int sizeOfCircleX = (int)((double)(this.getWidth() - topXShift - bottomXShift) / boardSize);
					int sizeOfCircleY = (int)((double)(this.getHeight() - topYShift - bottomYShift) / boardSize);
					int positionX = (int)((double)(this.getWidth() - topXShift - bottomXShift) / boardSize * i)  + topXShift;
					int positionY = (int)((double)(this.getHeight() - topYShift - bottomYShift) / boardSize * j)  + topYShift;
					g.setColor(Color.red);
					g.drawOval(positionX, positionY, sizeOfCircleX, sizeOfCircleY);
				} else if (board.getSymbolAtPosition(i, j) == BoardSymbol.CROSS) {
					int positionXFrom = (int)(((double)(this.getWidth() - topXShift - bottomXShift) / boardSize) * i) + topXShift;
					int positionYFrom = (int)(((double)(this.getHeight()- topYShift - bottomYShift) / boardSize) * j) + topYShift;
					int positionXTo = (int)(((double)(this.getWidth() - topXShift - bottomXShift) / boardSize) * (i+1)) + topXShift;
					int positionYTo = (int)(((double)(this.getHeight() - topYShift - bottomYShift) / boardSize) * (j+1)) + topYShift;
					g.setColor(Color.blue);
					g.drawLine(positionXFrom, positionYFrom, positionXTo, positionYTo);
				g	.drawLine(positionXTo, positionYFrom, positionXFrom, positionYTo);
				}
			}
		}
	}
}
